checks:
    javascript:
        no_var: true
        no_param_assign: true
        no_loop_var_assign: true
        no_implicit_undefined_return: true
        no_else_return: true
        no_alert: true
        eqeqeq: true
build:
    nodes:
        analysis:
            environment:
                node:
                    version: 6.0.0
            tests:
                override:
                    -
                        command: scss-lint-run
                        use_website_config: true
                    -
                        command: csslint-run
                        use_website_config: true

        tests: true
